### ISSUE TITLE
Introduce a tool for DB migrations

### ISSUE THREAD

**Issue by theneva** [rantlr/monorepo#10]

**Comment by runeh** [comment]
I can try hooking up knex for this if you like. I've only tried that one, so don't know if there's some other new hotness out there.

**Comment by theneva** [comment]
That would be really cool! I've briefly tried db-migrate which worked okay for a simple case but I don't have any experience with other tools :smile: if we settle on one tool for interacting with the DB we could ditch all the shell script stuff as well.
