### ISSUE TITLE
initing db requires psql installed

### ISSUE THREAD

**Issue by runeh** [rantlr/monorepo#8]
Either run it via docker, or update readme, or use `knex` or something else to talk to the db I guess?

**Comment by theneva** [comment]
I guess it makes sense to just run it in the postgres container that we already have instead of requiring postgres/psql to be installed on the host machine. Will have to play with it later

**Comment by theneva** [comment]
@runeh I made a hacky shell solution for this. Feel free to open a new issue if you have any better ideas :) I guess writing the "migrations" in javascript and just running the scripts with Node would also work…
